"""Vietnamese wording of the English seed questions, keyed by stable_key.

Seeded as APPROVED rows of `question_localizations`, so a vi-VN interview asks
the same approved question (same rubric and expected points) in Vietnamese.
Phrased the way an interviewer says it out loud; technical terms stay in
English as Vietnamese engineers use them.
"""
# ruff: noqa: E501

QUESTION_TEXT_VI: dict[str, str] = {
    # AI / GenAI / LLM / NLP
    "ai-fundamentals-bias-fairness": "Bias trong hệ thống AI là gì, và bạn dùng 2 kỹ thuật nào để phát hiện và giảm nó?",
    "ai-fundamentals-supervised-vs-unsupervised": "So sánh supervised và unsupervised learning, mỗi loại cho một ví dụ thực tế. Khi gán nhãn tốn kém thì ranh giới này quan trọng ra sao?",
    "ai-fundamentals-overfitting-regularization": "Overfitting là gì theo cách hiểu của bạn? Kể 3 kỹ thuật regularization và khi nào chọn từng cái.",
    "ai-fundamentals-evaluation-metrics": "Model phát hiện gian lận đạt accuracy 99% trên dữ liệu chỉ có 1% gian lận. Vì sao accuracy gây hiểu lầm, và bạn dùng metric nào thay thế?",
    "ai-fundamentals-model-deployment-drift": "Model chạy tốt offline nhưng sau 2 tháng production thì kém đi. Bạn chẩn đoán và xử lý data/model drift thế nào?",
    "genai-prompt-engineering-chain-of-thought": "Chain-of-thought prompting là gì, và cho một ví dụ ngắn nó giúp LLM suy luận đúng hơn ra sao?",
    "genai-hallucination-mitigation": "Nêu 2 cách ở mức kiến trúc hoặc prompt để giảm hallucination trong một ứng dụng production.",
    "genai-fine-tuning-vs-rag": "Với bài toán hỏi đáp theo domain riêng, so sánh fine-tuning và RAG. Khi nào chọn cái nào?",
    "llm-transformer-attention-mechanism": "Self-attention trong transformer hoạt động thế nào, và vì sao nó nắm được phụ thuộc xa trong văn bản?",
    "llm-context-window-limitations": "Context window giới hạn ảnh hưởng gì trong thực tế, và input vượt giới hạn thì bạn xử lý thế nào?",
    "llm-inference-latency-optimisation": "Nêu 3 kỹ thuật giảm latency khi serve LLM trong production mà không làm giảm nhiều chất lượng.",
    "nlp-tokenization-tradeoffs": "So sánh tokenization mức từ, sub-word (BPE/WordPiece) và ký tự. Khi nào dùng loại nào?",
    "nlp-named-entity-recognition-production": "Cần làm NER cho một domain y tế hẹp, ít dữ liệu gán nhãn. Bạn tiếp cận thế nào?",
    "nlp-semantic-search-implementation": "Làm semantic search trên 10 triệu tài liệu: bạn chọn embedding model, index và chiến lược retrieval ra sao?",
    # Python / FastAPI
    "python-mutable-default-and-scoping": "Dùng object mutable làm default argument trong Python thì chuyện gì xảy ra, vì sao dễ dính lỗi, và viết đúng thế nào?",
    "python-generators-vs-lists": "Khi nào bạn dùng generator thay vì list trong Python? Kể một lần lựa chọn này ảnh hưởng tới bộ nhớ hoặc latency.",
    "python-asyncio-blocking-call": "Endpoint async của FastAPI bị chậm sau khi ai đó thêm một lời gọi DB driver đồng bộ. Event loop bị gì, và bạn sửa thế nào?",
    "fastapi-dependency-injection": "Dependency injection trong FastAPI hoạt động thế nào, và bạn dùng nó để chia sẻ DB session an toàn ra sao?",
    "fastapi-pydantic-validation-boundary": "Rule nào nên nằm trong Pydantic request model, rule nào ở service layer? Cho ví dụ đặt sai chỗ gây lỗi.",
    "fastapi-background-work-and-timeouts": "Một endpoint FastAPI phải kích hoạt việc chạy 2 phút. Bạn cân nhắc những cách nào, trade-off ra sao, và báo trạng thái cho client thế nào?",
    # PostgreSQL / SQL / MySQL
    "postgresql-index-selection": "Query lọc 2 cột và sort cột thứ 3 bị chậm. Bạn đọc execution plan và chọn index thế nào?",
    "postgresql-transaction-isolation": "READ COMMITTED khác SERIALIZABLE trong PostgreSQL thế nào, và ở mức yếu hơn bạn dự đoán lỗi gì?",
    "postgresql-schema-migration-safety": "Thêm cột NOT NULL có default vào bảng lớn đang chạy mà không làm sập service, bạn làm thế nào?",
    "sql-join-semantics": "INNER JOIN khác LEFT JOIN thế nào, và cho một lỗi báo cáo do chọn sai loại join.",
    "sql-aggregation-and-grouping": "GROUP BY và HAVING khác WHERE thế nào? Cho ví dụ chuyển điều kiện giữa chúng làm đổi kết quả.",
    "sql-n-plus-one-queries": "N+1 query là gì, phát hiện nó trong service đang chạy thế nào, và 2 cách sửa?",
    "mysql-index-design": "Bạn chọn index cho bảng MySQL thế nào, và kiểm tra query có dùng index không ra sao?",
    "mysql-transactions-isolation": "Các mức isolation trong MySQL InnoDB là gì, và mức yếu hơn cho phép anomaly nào?",
    "mysql-joins-and-normalisation": "Khi nào bạn denormalize schema MySQL thay vì join, và cái giá phải trả là gì?",
    # Java / Spring
    "java-equals-hashcode-contract": "Ràng buộc giữa equals và hashCode trong Java là gì, và vi phạm thì hỏng chỗ nào?",
    "java-collections-concurrency": "Khi nào dùng ConcurrentHashMap thay vì synchronized HashMap? Nó thực sự đảm bảo điều gì?",
    "java-exception-design": "Ở service layer, bạn chọn checked hay unchecked exception thế nào? Cho ví dụ từ code của bạn.",
    "spring-boot-bean-scopes": "Bean singleton khác prototype trong Spring thế nào, và kể một lỗi do inject sai scope.",
    "spring-boot-transactional-pitfalls": "@Transactional trong Spring thực sự hoạt động ra sao, và khi nào nó âm thầm không có tác dụng?",
    "spring-boot-configuration-profiles": "Bạn tổ chức config cho local, staging và production trong Spring Boot thế nào mà không lộ secret?",
    # JavaScript / TypeScript / React
    "javascript-event-loop-microtasks": "Microtask khác macrotask trong event loop JavaScript thế nào, và thứ tự này gây bất ngờ ra sao trong thực tế?",
    "javascript-closures-in-loops": "Closure trong JavaScript giữ biến thế nào, và vì sao vòng lặp dùng var ngày trước cho ra sai giá trị?",
    "javascript-promise-error-handling": "Lỗi lan truyền thế nào qua promise chain và async/await? Kể một lần lỗi bị nuốt mất.",
    "typescript-structural-typing": "TypeScript dùng structural typing, nghĩa là gì trong thực tế? Cho ví dụ nó để lọt một giá trị không an toàn.",
    "typescript-unknown-vs-any": "Khi nào dùng unknown thay vì any, và narrow nó an toàn ở API boundary thế nào?",
    "typescript-generics-in-practice": "Kể một generic type hoặc function bạn viết thực sự đáng độ phức tạp, và làm sao biết khi nào không đáng.",
    "react-rendering-and-memo": "Khi nào React re-render component, và bạn điều tra trang re-render quá nhiều thế nào? Khi nào memo là cách sửa sai?",
    "react-effect-dependencies": "Bạn quyết định dependency array của useEffect thế nào, và kể một lỗi do đặt sai.",
    "react-state-placement": "State nên nằm ở component, shared store hay server? Kể một quyết định thực tế của bạn.",
    # Docker / Kubernetes / orchestration / cloud
    "docker-image-layers-and-size": "Layer và build cache của Docker hoạt động thế nào, và bạn giảm image 1,5 GB xuống đáng kể ra sao?",
    "docker-container-networking": "Hai container trong cùng compose project không gọi được nhau. Bạn chẩn đoán thế nào?",
    "docker-runtime-config-and-secrets": "Bạn truyền config và secret vào container thế nào mà không build chúng vào image?",
    "kubernetes-probes": "Liveness probe khác readiness probe thế nào, và cấu hình giống nhau thì hỏng gì?",
    "kubernetes-pod-crashloop-diagnosis": "Sau một lần release, deployment bị CrashLoopBackOff. Bạn chẩn đoán theo thứ tự nào?",
    "kubernetes-resource-requests-limits": "Resource request khác limit thế nào, và pod vượt từng loại thì chuyện gì xảy ra?",
    "orchestrator-why-orchestrate": "Container orchestrator như Kubernetes hay Docker Swarm giải quyết vấn đề gì so với chạy container bằng tay?",
    "orchestrator-health-and-rollout": "Orchestrator dựa vào đâu để biết container khỏe, và thiếu health check thì rollout hỏng thế nào?",
    "orchestrator-scaling-stateful": "Vì sao scale một service có state như database khó hơn API stateless trên orchestrator?",
    "aws-iam-least-privilege": "Cấp cho service quyền vào đúng một prefix của một S3 bucket thế nào, và kiểm tra policy không rộng hơn dự định ra sao?",
    "aws-compute-choice": "Service HTTP mới, traffic đột biến: chọn Lambda, ECS hay EC2? Điều gì khiến bạn đổi ý?",
    "aws-cost-investigation": "Hóa đơn AWS tăng gấp đôi trong khi traffic không đổi. Bạn tìm nguyên nhân thế nào?",
    # Git / HTTP / JSON / XML
    "git-merge-vs-rebase": "Khi nào bạn rebase, khi nào merge? Kể một lần lựa chọn này quan trọng với team.",
    "git-recovering-a-bad-commit": "Bạn push commit làm hỏng main và người khác đã pull về. Bạn khắc phục thế nào?",
    "git-branching-strategy": "Branching strategy ở dự án gần nhất của bạn thế nào, và bạn muốn đổi điều gì?",
    "http-status-code-semantics": "Bạn chọn 400, 401, 403, 404 hay 409 cho request lỗi thế nào? Mỗi mã cho một ví dụ.",
    "http-idempotency-and-retries": "Method HTTP nào nên idempotent, và làm endpoint thanh toán retry an toàn thế nào?",
    "http-caching-headers": "ETag và Cache-Control phối hợp thế nào, và kể một lần cache trả về dữ liệu cũ.",
    "json-schema-evolution": "Thêm field vào JSON response thế nào để không phá client cũ? Thay đổi nào không an toàn?",
    "json-parsing-untrusted-input": "Khi parse JSON từ client không tin cậy, bạn validate những gì và ở tầng nào?",
    "json-numeric-precision": "Số nguyên lớn hoặc tiền đi qua JSON có thể sai thế nào, và bạn xử lý ra sao?",
    "xml-namespaces-and-xsd-validation": "Đối tác gửi XML (vd SOAP hoặc hóa đơn). Bạn xử lý namespace và validate với XSD trước khi xử lý thế nào?",
    "xml-vs-json-mapping": "Khi nào vẫn chọn XML thay vì JSON, và chuyển đổi giữa hai dạng có thể mất thông tin gì?",
    "xml-xxe-and-parser-hardening": "Tấn công XXE hoặc entity expansion vào endpoint nhận XML hoạt động thế nào, và cấu hình parser để chặn ra sao?",
    # Machine learning
    "ml-train-test-leakage": "Data leakage trong pipeline ML là gì, phát hiện thế nào, và kể một lần nó làm metric đẹp giả.",
    "ml-metric-selection": "Bài toán phân loại mất cân bằng nặng: bạn tối ưu metric nào, và vì sao accuracy gây hiểu lầm?",
    "ml-model-in-production": "Model tốt offline nhưng kém đi trên production. Bạn điều tra thế nào?",
    # Mobile
    "android-activity-lifecycle": "Đi qua vòng đời Activity trên Android, và bạn lưu state ở đâu để xoay màn hình không mất?",
    "android-background-work": "Chạy việc phải sống sót khi app vào background hoặc máy khởi động lại thế nào?",
    "android-memory-leaks": "App Android hay leak memory ở đâu, và bạn xác nhận leak thay vì đoán thế nào?",
    "ios-arc-and-retain-cycles": "ARC quản lý bộ nhớ trên iOS thế nào, retain cycle hình thành ra sao, và phá nó thế nào?",
    "ios-view-lifecycle": "Vòng đời UIViewController thế nào, và việc không được chạy mỗi lần hiển thị thì đặt ở đâu?",
    "ios-main-thread-responsiveness": "UI bị giật khi đang tải dữ liệu. Nhiều khả năng chuyện gì đang xảy ra, và bạn sửa thế nào?",
    "kotlin-null-safety": "Type system của Kotlin xử lý null thế nào, và khi nào bạn vẫn dùng non-null assertion (!!)?",
    "kotlin-coroutines-scope": "Structured concurrency trong coroutine Kotlin giải quyết vấn đề gì, và launch sai scope thì sao?",
    "kotlin-data-classes-and-equality": "Data class trong Kotlin cho bạn sẵn những gì, và khi nào không nên dùng?",
    # C++ / Unity / C# / .NET
    "cpp-raii-and-ownership": "RAII là gì và smart pointer thể hiện ownership thế nào? Khi nào vẫn dùng raw pointer?",
    "cpp-undefined-behaviour": "Cho 2 ví dụ undefined behaviour trong C++, và vì sao chúng nguy hiểm chứ không chỉ là sai?",
    "cpp-copy-vs-move": "Copy khác move semantics thế nào, và kể một lần làm sai gây tốn hiệu năng.",
    "unity-update-loop-performance": "Trong Unity cái gì chạy mỗi frame, và bạn tìm nguyên nhân scene tụt dưới frame rate mục tiêu thế nào?",
    "unity-prefabs-and-scene-structure": "Bạn tổ chức prefab và scene thế nào để nhiều người làm chung game mà không conflict liên tục?",
    "unity-physics-and-fixedupdate": "Update khác FixedUpdate thế nào, và kể một lỗi do đặt code physics sai chỗ.",
    "csharp-value-vs-reference": "Value type và reference type trong C# khác nhau thế nào, và một lỗi do nhầm hai loại này.",
    "csharp-async-await": "async/await trong C# hoạt động thế nào, và vì sao gọi .Result trên task có thể gây deadlock?",
    "csharp-idisposable-and-gc": "Garbage collector đã giải phóng bộ nhớ thì khi nào bạn vẫn cần IDisposable trong C#?",
    "dotnet-dependency-injection-lifetimes": "Singleton, Scoped và Transient trong DI của ASP.NET Core khác nhau thế nào, và một lỗi do chọn sai lifetime.",
    "dotnet-middleware-pipeline": "Middleware pipeline của ASP.NET Core xử lý request thế nào, và vì sao thứ tự middleware quan trọng?",
    "dotnet-ef-core-performance": "Endpoint dùng Entity Framework Core bị chậm. Bạn xem gì trước, và sửa N+1 query thế nào?",
    # Ops: monitoring / Linux / CI-CD
    "monitoring-metrics-logs-traces": "Metrics, logs và traces khác nhau thế nào, và API đột nhiên chậm thì bạn xem cái nào trước?",
    "monitoring-alerting-on-symptoms": "Bạn quyết định cái gì đáng alert gọi người dậy lúc nửa đêm thế nào, và tránh alert fatigue ra sao?",
    "monitoring-slo-error-budget": "SLI, SLO và error budget là gì, và error budget thay đổi việc team ưu tiên làm thế nào?",
    "linux-process-and-signals": "Một process trên server Linux ăn 100% CPU và không dừng. Bạn điều tra và dừng nó an toàn thế nào?",
    "linux-permissions-and-ownership": "Permission và ownership file trên Linux hoạt động thế nào, và vì sao chạy service bằng root là rủi ro?",
    "linux-disk-full-incident": "Server báo đầy ổ đĩa nhưng không tìm thấy file lớn. Nguyên nhân có thể là gì và tìm ra thế nào?",
    "cicd-pipeline-stages": "Pipeline CI/CD bạn từng làm có những stage nào, và điều gì nên làm pipeline fail?",
    "cicd-safe-deployments": "So sánh rolling, blue-green và canary. Thay đổi rủi ro thì chọn cách nào, và rollback ra sao?",
    "cicd-flaky-and-slow-builds": "Pipeline của team mất 40 phút và fail ngẫu nhiên. Bạn làm nó nhanh và đáng tin lại thế nào?",
    # Redis / Kafka
    "redis-cache-invalidation": "Bạn cache API response bằng Redis thế nào, và giữ cache nhất quán khi dữ liệu gốc đổi ra sao?",
    "redis-data-structures": "Kể 3 cấu trúc dữ liệu Redis ngoài string và mỗi loại một use case thực tế.",
    "redis-cache-stampede": "Cache stampede là gì, và bảo vệ database khi một hot key Redis hết hạn thế nào?",
    "kafka-partitions-and-ordering": "Partition ảnh hưởng ordering và throughput trong Kafka thế nào, và giữ thứ tự event của một user ra sao?",
    "kafka-consumer-groups": "Consumer group và offset trong Kafka là gì? Consumer crash trước khi commit offset thì sao?",
    "kafka-idempotent-processing": "Kafka có thể giao một message nhiều lần. Bạn thiết kế consumer thế nào để message trùng không làm sai kết quả?",
}
