from typing import Final

CANDIDATE: Final = "CANDIDATE"
ADMIN: Final = "ADMIN"
QUESTION_AUTHOR: Final = "QUESTION_AUTHOR"
QUESTION_REVIEWER: Final = "QUESTION_REVIEWER"
DATA_CURATOR: Final = "DATA_CURATOR"
QUESTION_BANK_ADMIN: Final = "QUESTION_BANK_ADMIN"
INTERNAL_ACTORS: Final = frozenset({ADMIN, QUESTION_AUTHOR, QUESTION_REVIEWER, DATA_CURATOR, QUESTION_BANK_ADMIN})
USER_ROLES: Final = frozenset({CANDIDATE, *INTERNAL_ACTORS})
